//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArmLicence
{
    using System;
    using System.Collections.Generic;
    
    public partial class AuthorityMas
    {
        public string Authorityid { get; set; }
        public string AuthorityName { get; set; }
        public string Districtid { get; set; }
        public byte[] sign { get; set; }
    }
}
