//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArmLicence
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ArmEntities : DbContext
    {
        public ArmEntities()
            : base("name=ArmEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblloghis> tblloghis { get; set; }
        public virtual DbSet<tbluser> tbluser { get; set; }
        public virtual DbSet<DistrictMas> DistrictMas { get; set; }
        public virtual DbSet<AuthorityMas> AuthorityMas { get; set; }
        public virtual DbSet<tblweapon> tblweapon { get; set; }
        public virtual DbSet<tblweaponholder> tblweaponholder { get; set; }
    }
}
