//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArmLicence
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbluser
    {
        public int Id { get; set; }
        public string Uid { get; set; }
        public string Pass { get; set; }
        public string Mobile { get; set; }
        public Nullable<bool> status { get; set; }
        public string Authorityid { get; set; }
        public string usertype { get; set; }
    }
}
