//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArmLicence
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblweaponholder
    {
        public string licNo { get; set; }
        public string name { get; set; }
        public string fname { get; set; }
        public string address { get; set; }
        public string mobile { get; set; }
        public string area { get; set; }
        public string licType { get; set; }
        public string UIN { get; set; }
        public Nullable<System.DateTime> imgUpdate { get; set; }
        public Nullable<System.DateTime> printDate { get; set; }
        public Nullable<System.DateTime> uploadDate { get; set; }
        public string issueDate { get; set; }
        public string expiryDate { get; set; }
        public byte[] photo { get; set; }
        public byte[] sign { get; set; }
        public Nullable<int> AuthorityId { get; set; }
        public int status { get; set; }
        public string Remarks { get; set; }
        public string trnsid { get; set; }
    }
}
