//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArmLicence
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblweaponholder
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblweaponholder()
        {
            this.tblweapon = new HashSet<tblweapon>();
        }
    
        public string licNo { get; set; }
        public string name { get; set; }
        public string fname { get; set; }
        public string address { get; set; }
        public string mobile { get; set; }
        public string area { get; set; }
        public string licType { get; set; }
        public string UIN { get; set; }
        public Nullable<System.DateTime> imgUpdate { get; set; }
        public Nullable<System.DateTime> printDate { get; set; }
        public Nullable<System.DateTime> uploadDate { get; set; }
        public string issueDate { get; set; }
        public string expiryDate { get; set; }
        public byte[] photo { get; set; }
        public byte[] sign { get; set; }
        public Nullable<int> AuthorityId { get; set; }
        public Nullable<int> status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblweapon> tblweapon { get; set; }
    }
}
